import { Changa } from 'next/font/google'; // ✅ Fixed import
import type { Metadata } from "next";
import "./globals.scss";
import { Providers } from "@/redux/provider";

const changa = Changa({
  weight: ['400', '500', '700'],
  subsets: ['arabic'],
});

export const metadata: Metadata = {
  title: "Luqya - Business & Finance Next js Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <body className={changa.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
